// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bpvxlqlbtmnxjvfxvifg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJwdnhscWxidG1ueGp2Znh2aWZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3MjIxNzAsImV4cCI6MjA2MDI5ODE3MH0.IWklukZrrJggIQrVTt1zlHMNBqCiqLcDg6Plg68XY0M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);